# Generated by packaging/homebrew/formula.sh in https://github.com/pungoyal/dotsync.
# Every release replaces this file; changes made here are lost.
class Dotsync < Formula
  desc "Set-and-forget dotfile sync for macOS and Linux"
  homepage "https://pungoyal.github.io/dotsync/"
  version "0.6.0"
  license "MIT"

  livecheck do
    url :stable
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/pungoyal/dotsync/releases/download/v0.6.0/dotsync_0.6.0_darwin_arm64.tar.gz"
      sha256 "9324cb5dcdb73717efb70089ddf7caa79d91f22501019cf6a8c7f8cae0608260"
    end
    on_intel do
      url "https://github.com/pungoyal/dotsync/releases/download/v0.6.0/dotsync_0.6.0_darwin_amd64.tar.gz"
      sha256 "e4c708150da92d3c6720dc6099497c1d8395664d36806d169ab2ba8a21316bcb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/pungoyal/dotsync/releases/download/v0.6.0/dotsync_0.6.0_linux_arm64.tar.gz"
      sha256 "99b11b49ce6ff5a3c5579e62361964495a61d669333f9c411f87f633806b4f31"
    end
    on_intel do
      url "https://github.com/pungoyal/dotsync/releases/download/v0.6.0/dotsync_0.6.0_linux_amd64.tar.gz"
      sha256 "af1f1b6f664bdb2a013c1405da480cb4776a152b2b50e563040f2119e9d9bfc7"
    end
  end

  def install
    bin.install "dotsync"
    man1.install "manpages/dotsync.1.gz"
  end

  def caveats
    <<~EOS
      Homebrew keeps dotsync up to date: use `brew upgrade dotsync` instead of `dotsync update`.
      To get started: dotsync init <git-url>
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dotsync version")

    # A full round trip: set up against a local remote, manage a file, check it was pushed.
    system "git", "init", "--quiet", "--bare", "remote.git"
    (testpath/".testrc").write "hello\n"
    system bin/"dotsync", "init", "--no-agent", "--no-install", "file://#{testpath}/remote.git"
    system bin/"dotsync", "add", testpath/".testrc"
    assert_equal "hello\n", shell_output("git -C remote.git show main:files/testrc")
  end
end
